### ISSUE TITLE
unresolved external symbol  g2o::G2OBatchStatistics 

### ISSUE THREAD

**Issue by antithing** [bikong2/ORB_SLAM2_dense#1]
Hi, and thank you for making this code available. I am having problems compiling, and get an error:

`LNK2019	unresolved external symbol "protected: static struct g2o::G2OBatchStatistics * g2o::G2OBatchStatistics::_globalStats" (?_globalStats@G2OBatchStatistics@g2o@@1PEAU12@EA) referenced in function "public: virtual bool __cdecl g2o::BlockSolver<struct g2o::BlockSolverTraits<6,3> >::computeMarginals(class g2o::SparseBlockMatrix<class Eigen::Matrix<double,-1,-1,0,-1,-1> > &,class std::vector<struct std::pair<int,int>,class std::allocator<struct std::pair<int,int> > > const &)" (?computeMarginals@?$BlockSolver@U?$BlockSolverTraits@$05$02@g2o@@@g2o@@UEAA_NAEAV?$SparseBlockMatrix@V?$Matrix@N$0?0$0?0$0A@$0?0$0?0@Eigen@@@2@AEBV?$vector@U?$pair@HH@std@@V?$allocator@U?$pair@HH@std@@@2@@std@@@Z)	ORB_SLAM2	D:\ORB_SLAM2_dense-master\build\Optimizer.obj	`

I have tried the g2o version that works with vanilla ORBSLAM2, and the one that is included here. What could i be missing?

Thanks again.

**Comment by zz1120122573** [comment]
Hi @antithing 
I also have this problem, have you solved it? How?

Thanks
